'''
Created on Mar 18, 2014

@author: jikhanjung
'''
'''
Created on Mar 9, 2014

@author: jikhanjung
'''
X_INDEX = 0
Y_INDEX = 1
Z_INDEX = 2

ID_NONE = 0
ID_ROUND = 1
ID_ENCRUSTING = 2
ID_PLATY = 3

MAX_COLONY_SIZE = 800
ATTENUATION_COEFFICIENT = 4.6 / 50.0
SURFACE_IRRADIANCE = 1361
MAX_IRRADIANCE = 100
REFLECTION_RATE = 0.05
GROWTH_CONSTANT = 10
LATERAL_GROWTH_PERIOD = 12
LATERAL_GROWTH_CRITERION = 0.1
NEIGHBOR_DISTANCE_MULTIPLIER = 2
POLYP_RADIUS = 2.5
DEPTH = 1
ZOOM = 1.0
